import express from 'express';
import { supabase } from '../services/supabase.service';
import { translateText } from '../services/groq.service';
import { logMessage } from '../services/logMessage.service';
import { sendToPhone } from '../services/whatsapp.service';

const router = express.Router();
router.get('/', async (req, res) => { const date = (req.query.date as string) || new Date().toISOString().split('T')[0]; const classFilter = req.query.class as string | undefined; const { data, error } = await supabase.from('attendance').select('*, students(name, class, parent_phone)').eq('date', date); if (error) return res.status(500).json({ error: error.message }); const filtered = classFilter ? data.filter((a: any) => a.students.class === classFilter) : data; res.json(filtered); });
router.post('/mark', async (req, res) => { try { const { student_id, status, date } = req.body; const attendanceDate = date || new Date().toISOString().split('T')[0]; const { data, error } = await supabase.from('attendance').upsert([{ student_id, date: attendanceDate, status }], { onConflict: 'student_id,date' }).select(); if (error) throw error; if (status === 'absent') { const { data: student } = await supabase.from('students').select('*').eq('id', student_id).single(); if (student) { const english = `Your child ${student.name} was marked absent today. Please confirm or inform the school if this is a mistake.`; const tamil = await translateText(english); await sendToPhone(student.parent_phone, `${english}\n\n${tamil}`); await logMessage(english, tamil, `Absence Alert — ${student.name}`, 1); } } res.json(data[0]); } catch (err: any) { console.error(err); res.status(500).json({ error: err.message }); } });
router.get('/summary', async (req, res) => { try { const date = (req.query.date as string) || new Date().toISOString().split('T')[0]; const { data: allStudents } = await supabase.from('students').select('id, class'); const { data: attendanceToday } = await supabase.from('attendance').select('student_id, status').eq('date', date); const attMap: Record<string, string> = {}; (attendanceToday || []).forEach((a: any) => (attMap[a.student_id] = a.status)); const classOrder = ['LKG', 'UKG', '1', '2', '3', '4', '5', '6', '7', '8']; const summary = classOrder.map((cls) => { const classStudents = (allStudents || []).filter((s: any) => s.class === cls); const present = classStudents.filter((s: any) => attMap[s.id] === 'present').length; const absent = classStudents.filter((s: any) => attMap[s.id] === 'absent').length; return { class: cls, total: classStudents.length, present, absent, unmarked: classStudents.length - present - absent }; }).filter((c) => c.total > 0); res.json({ date, summary }); } catch (err: any) { console.error(err); res.status(500).json({ error: err.message }); } });
export default router;
