import express from 'express';
import multer from 'multer';
import fs from 'fs';
import { MessageMedia } from 'whatsapp-web.js';
import { supabase } from '../services/supabase.service';
import { logMessage } from '../services/logMessage.service';
import { waClient, waReady } from '../services/whatsapp.service';

const router = express.Router();
const upload = multer({ dest: 'uploads/', limits: { fileSize: 16 * 1024 * 1024 } });
router.get('/', async (req, res) => { const { data, error } = await supabase.from('events').select('*').order('event_date'); if (error) return res.status(500).json({ error: error.message }); res.json(data); });
router.post('/', async (req, res) => { const { title, event_date, notes } = req.body; const { data, error } = await supabase.from('events').insert([{ title, event_date, notes }]).select(); if (error) return res.status(500).json({ error: error.message }); res.json(data[0]); });
router.delete('/:id', async (req, res) => { const { error } = await supabase.from('events').delete().eq('id', req.params.id); if (error) return res.status(500).json({ error: error.message }); res.json({ success: true }); });
router.post('/:id/media', upload.array('media', 10), async (req, res) => { try { const files = req.files as Express.Multer.File[]; if (!files || files.length === 0) return res.status(400).json({ error: 'No files provided' }); const { caption } = req.body; const uploaded = []; for (const file of files) { const fileExt = file.originalname.split('.').pop(); const fileName = `${req.params.id}/${Date.now()}-${Math.random().toString(36).slice(2)}.${fileExt}`; const fileData = fs.readFileSync(file.path); const { error: uploadError } = await supabase.storage.from('event-media').upload(fileName, fileData, { contentType: file.mimetype }); if (uploadError) throw uploadError; const { data: publicUrlData } = supabase.storage.from('event-media').getPublicUrl(fileName); const { data: mediaRow } = await supabase.from('event_media').insert([{ event_id: req.params.id, media_url: publicUrlData.publicUrl, media_type: file.mimetype.startsWith('video') ? 'video' : 'image', caption }]).select(); uploaded.push(mediaRow?.[0]); fs.unlinkSync(file.path); } res.json(uploaded); } catch (err: any) { console.error(err); res.status(500).json({ error: err.message }); } });
router.get('/:id/media', async (req, res) => { const { data, error } = await supabase.from('event_media').select('*').eq('event_id', req.params.id).order('uploaded_at'); if (error) return res.status(500).json({ error: error.message }); res.json(data); });
router.post('/:id/send', async (req, res) => { try { const { phones, mediaIds } = req.body; const { data: mediaItems } = await supabase.from('event_media').select('*').in('id', mediaIds); const { data: event } = await supabase.from('events').select('*').eq('id', req.params.id).single(); for (const phone of phones) { const cleanPhone = phone.replace(/[^0-9]/g, ''); if (!waReady) continue; const numberId = await waClient.getNumberId(cleanPhone); if (!numberId) continue; for (let i = 0; i < (mediaItems || []).length; i++) { const item = mediaItems![i]; await waClient.sendMessage(numberId._serialized, await MessageMedia.fromUrl(item.media_url), i === 0 ? { caption: item.caption || event?.title } : {}); } } await logMessage(event?.title || 'Event photos', '', 'Event Media', phones.length); res.json({ success: true }); } catch (err: any) { console.error(err); res.status(500).json({ error: err.message }); } });
router.delete('/:eventId/media/:mediaId', async (req, res) => { try { const { data: mediaItem } = await supabase.from('event_media').select('*').eq('id', req.params.mediaId).single(); if (mediaItem) { const urlParts = mediaItem.media_url.split('/event-media/'); const filePath = urlParts[1]; if (filePath) await supabase.storage.from('event-media').remove([filePath]); } const { error } = await supabase.from('event_media').delete().eq('id', req.params.mediaId); if (error) throw error; res.json({ success: true }); } catch (err: any) { console.error(err); res.status(500).json({ error: err.message }); } });
export default router;
