import express from 'express';
import multer from 'multer';
import fs from 'fs';
import QRCode from 'qrcode';
import { supabase } from '../services/supabase.service';
import { groq } from '../services/groq.service';
import { currentQR, waReady } from '../services/whatsapp.service';

const router = express.Router();
const upload = multer({ dest: 'uploads/', limits: { fileSize: 16 * 1024 * 1024 } });
router.get('/qr', async (req, res) => { if (waReady) return res.send('<h2>✅ WhatsApp is already connected!</h2>'); if (!currentQR) return res.send('<h2>⏳ Waiting for QR code to generate... refresh in a few seconds.</h2><script>setTimeout(() => location.reload(), 3000);</script>'); const qrImage = await QRCode.toDataURL(currentQR); res.send(`<html><body style="display:flex;flex-direction:column;align-items:center;justify-content:center;height:100vh;font-family:sans-serif;"><h2>Scan this with WhatsApp → Linked Devices</h2><img src="${qrImage}" style="width:300px;height:300px;" /><p>This page auto-refreshes every 60 seconds</p><script>setTimeout(() => location.reload(), 60000);</script></body></html>`); });
router.post('/api/check-clarity', async (req, res) => { try { const { text } = req.body; if (!text?.trim()) return res.json({ hasIssue: false }); const completion = await groq.chat.completions.create({ model: 'openai/gpt-oss-20b', messages: [{ role: 'user', content: `Review this school announcement for grammar, clarity, or awkward phrasing issues that a busy admin might have typed quickly:\n\n"${text}"\n\nIf it's clear and fine as-is, respond with exactly: OK\nIf there's a real issue worth fixing, respond with exactly: ISSUE: <a corrected/clearer version of the same message, keeping the same meaning and tone>` }] }); const result = completion.choices[0].message.content || ''; if (result.trim().toUpperCase().startsWith('OK')) res.json({ hasIssue: false }); else res.json({ hasIssue: true, suggestion: result.replace(/^ISSUE:\s*/i, '').trim() }); } catch (err: any) { console.error('Clarity check error:', err); res.status(500).json({ error: err.message }); } });
router.get('/api/system-status', async (req, res) => { try { const { error: dbError } = await supabase.from('students').select('id').limit(1); res.json({ backendRunning: true, whatsappReady: waReady, databaseConnected: !dbError, serverTime: new Date().toISOString() }); } catch (err) { res.status(500).json({ backendRunning: true, whatsappReady: false, databaseConnected: false, error: 'Status check failed' }); } });
router.post('/api/generate-caption', upload.single('image'), async (req, res) => { try { if (!req.file) return res.status(400).json({ error: 'No image provided' }); const imageData = fs.readFileSync(req.file.path); const completion = await groq.chat.completions.create({ model: 'qwen/qwen3.6-27b', messages: [{ role: 'user', content: [{ type: 'text', text: 'Write a short, warm caption (under 15 words) for this school event photo, suitable for a parent WhatsApp group. Just the caption, nothing else.' }, { type: 'image_url', image_url: { url: `data:${req.file.mimetype};base64,${imageData.toString('base64')}` } }] as any }] }); fs.unlinkSync(req.file.path); res.json({ caption: completion.choices[0].message.content }); } catch (err: any) { console.error('Caption generation error:', err); res.status(500).json({ error: err.message }); } });
export default router;
